config-version = 2

after-startup-command = []
start-at-login = false
auto-reload-config = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

persistent-workspaces = [
    '1-look',
    '2-build',
    '3-org',
    '4-med',
    '5-temp',
]

on-mode-changed = []
focus-follows-mouse.enabled = false
key-mapping.preset = 'qwerty'

on-window-detected = [
    { if = 'test %{app-bundle-id} = com.apple.Safari', run = 'move-node-to-workspace 1-look' },
    { if = 'test %{app-bundle-id} = com.apple.iCal || test %{app-bundle-id} = com.apple.reminders || test %{app-bundle-id} = com.apple.mail', run = 'move-node-to-workspace 3-org' },
    { if = 'test %{app-bundle-id} = com.mitchellh.ghostty || test %{app-bundle-id} = com.apple.Terminal', run = 'move-node-to-workspace 2-build' },
    { if = 'test %{app-bundle-id} = com.spotify.client', run = 'move-node-to-workspace 4-med' },
]

gaps.inner.horizontal = 10
gaps.inner.vertical = 10
gaps.outer.left = 10
gaps.outer.bottom = 10
gaps.outer.top = 10
gaps.outer.right = 10

[mode.main.binding]
    alt-slash = 'layout tiles vertical horizontal'
    alt-comma = 'layout accordion vertical horizontal'

    alt-h = 'focus --wrap-around left'
    alt-j = 'focus --wrap-around down'
    alt-k = 'focus --wrap-around up'
    alt-l = 'focus --wrap-around right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-y = 'workspace --auto-back-and-forth 1-look'
    alt-u = 'workspace --auto-back-and-forth 2-build'
    alt-i = 'workspace --auto-back-and-forth 3-org'
    alt-o = 'workspace --auto-back-and-forth 4-med'
    alt-p = 'workspace --auto-back-and-forth 5-temp'

    alt-shift-y = 'move-node-to-workspace 1-look'
    alt-shift-u = 'move-node-to-workspace 2-build'
    alt-shift-i = 'move-node-to-workspace 3-org'
    alt-shift-o = 'move-node-to-workspace 4-med'
    alt-shift-p = 'move-node-to-workspace 5-temp'

    alt-ctrl-shift-h = 'move-node-to-monitor --focus-follows-window --wrap-around left'
    alt-ctrl-shift-j = 'move-node-to-monitor --focus-follows-window --wrap-around down'
    alt-ctrl-shift-k = 'move-node-to-monitor --focus-follows-window --wrap-around up'
    alt-ctrl-shift-l = 'move-node-to-monitor --focus-follows-window --wrap-around right'

    alt-leftSquareBracket = 'workspace --wrap-around prev'
    alt-rightSquareBracket = 'workspace --wrap-around next'

    alt-f = 'fullscreen'
    alt-tab = 'focus-back-and-forth || workspace-back-and-forth'
    alt-m = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-0 = 'balance-sizes'

    alt-ctrl-h = 'focus-monitor --wrap-around left'
    alt-ctrl-j = 'focus-monitor --wrap-around down'
    alt-ctrl-k = 'focus-monitor --wrap-around up'
    alt-ctrl-l = 'focus-monitor --wrap-around right'

    alt-space = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']
