#################################################
# This file is a sample of some things you 
# can do with this leader key setup. It's active
# right now! Set leader_key below and try it! The 
# lua prioritizes home.toml, then work.toml,
# then falls back to this sample.toml. If you
# want different profile names, you can add it
# to the list in ~/.hammerspoon/init.lua. 
#################################################

# settings
leader_key = "§"        # required, the leader key that starts the sequence
leader_key_mods = ""      # optional, default "", not recommended - a dedicated leader key is better
                             # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = true    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps
key_maps_per_line = 1     # optional, default 5, number of key maps per line in the ui

g = ["Ghostty", " ghostty"]
'.' = ["repeat", " repeat"]
c = ["function:openAlfredClipboard", " clipboard"]
# b = ["cmd:osascript -e 'tell application id \"com.runningwithcrayons.Alfred\" to search \"m \"'", " Menu Search"]

[f] # FINDER 
label = "|  finder"
f = "Finder"
d = ["cmd:open ~/Downloads", "downloads"]
k = ["cmd:open ~/Desktop", "desktop"]
r = ["cmd:open '/Users/fungus/Library/Saved Searches/Recent.savedSearch'", "recents"]
o = ["cmd:open ~/OneDrive", "onedrive"]
h = ["cmd:open ~/", "fungus"]
D = ["cmd: open /Users/fungus/Library/CloudStorage/OneDrive-Personal/Documents/admin/dopamine_menu_v1.pdf", "Dopa menu"]
# ~/.hammerspoon/home.toml


[k]
label = "|  maestro"
g = ["hs:hs.urlevent.openURL('kmtrigger://macro=open_in_ghostty')", "Open ghostty"]
m = ["hs:hs.urlevent.openURL('kmtrigger://macro=move_reminder')", "Move reminders"]
k = ["hs:hs.urlevent.openURL('kmtrigger://macro=search_km')", "Search KM"]
o = ["hs:hs.urlevent.openURL('kmtrigger://macro=ocr_clipboard')", "Ocr clipboard"]
s = ["hs:hs.urlevent.openURL('kmtrigger://macro=screenshot_all_monitors')", "ss all monitors"]
a = ["hs:hs.urlevent.openURL('kmtrigger://macro=screenshot_active_monitor')", "ss active monitor"]
# o = ["hs:hs.urlevent.openURL('kmtrigger://macro=screenshot_active_monitor')", "ss active monitor"]

[m]
label = "|  media"
'space' = ["hs:hs.eventtap.event.newSystemKeyEvent('PLAY', true):post(); hs.eventtap.event.newSystemKeyEvent('PLAY', false):post()", "Play/Pause"]
"n" = ["hs:hs.eventtap.event.newSystemKeyEvent('NEXT', true):post(); hs.eventtap.event.newSystemKeyEvent('NEXT', false):post()", "Next Track"]
"p" = ["hs:hs.eventtap.event.newSystemKeyEvent('PREVIOUS', true):post(); hs.eventtap.event.newSystemKeyEvent('PREVIOUS', false):post()", "Previous Track"]




[a] 
label = "|  app actions"
[a.s]
label = "|  safari"
s = ["menu:Safari|Bookmarks>Show Start Page", "Start page"] # select menu items (specific app)
[a.o]
label = "|  ollama"
q = ["cmd: /Users/fungus/Library/CloudStorage/OneDrive-Personal/Documents/tech-bible/automation/scripts/stop-ollama.sh", "quit ollama"]
s = ["cmd: /opt/homebrew/bin/ollama serve > /dev/null 2>&1", "start ollama"]
[a.t]
label = "|  tailscale"
t = ["cmd:pgrep -x Tailscale > /dev/null && (osascript -e 'quit app \"Tailscale\"' && osascript -e 'display notification \"Tailscale quit\" with title \"Tailscale\"') || (open -a Tailscale && osascript -e 'display notification \"Tailscale launched\" with title \"Tailscale\"')", " toggle tailscale"]





# [h]
# label = "[helpers]"
# h = "shortcut: cmd shift 4"



# use prefixes for special actions
# [p]
# label = "[prefixes]"
# t = "text:sam@saml.dev"       # types "sam@saml.dev"
# z = "cmd:code ~/.zshrc"       # run any terminal command
# x = "code: ~/.zshrc"          # open a file or directory in VS Code
# s = "shortcut:cmd shift 4"    # trigger a keyboard shortcut
# w = "menu:File>New Window"    # select menu items (frontmost app)
# n = "menu:Safari|File>New Tab" # select menu items (specific app)
# r = "reload"                  # reserved for reloading your hammerspoon config (helpful when auto_reload is false)
# i = "input:https://google.com/search?q={input}" # capture input and insert it into any other action
# c = "clipboard:text:{clipboard}"                # insert clipboard contents into any other action


# window management
[w]
label = "|  window"
h = ["window:left-half", "left half"]
l = ["window:right-half", "right half"]
k = ["window:top-half", "top half"]
j = ["window:bottom-half", "bottom half"]
c = ["window:center-half", "center half"]
u = ["window:top-left", "top-left quadrant"]
i = ["window:top-right", "top-right quadrant"]
n = ["window:bottom-left", "bottom-left quadrant"]
m = ["window:bottom-right", "bottom-right quadrant"]
f = ["window:fullscreen", "fullscreen"]
x = ["window:maximized", "maximize"]
t = ["menu:View>Float on Top", "float on top (app menu)"]
s = ["hs:hs.pasteboard.setContents(hs.inspect(hs.window.focusedWindow():size()))", "Window size"]



# for quick access to your config
# [h]
# label = "[hammerspoon]"
# c = "code: ~/.hammerspoon"
# r = "reload" # reserved for reloading your hammerspoon config (helpful when auto_reload is false)


# glhf :) share your cool ideas with me on
# twitter @saml_dev - <leader> l m t
# bluesky @saml.dev - <leader> l m b
# github saml-dev   - <leader> l m g
